### PR TITLE
fix: issue#4 and issue#6

### LINKED ISSUE #4: Application becomes stuck after trying to transfer less than 61 CKB.
If you try to transfer less than 61 CKB, you receive this error:

Then you receive this error which cannot be bypassed:

### LINKED ISSUE #6: The Early Access Beta warning only displays on the Transfer CKB page.
The Early Access Beta warning only displays on the Transfer CKB page. This message is applicable to all pages so it makes sense to have it present eveywhere.

### PR DESCRIPTION
**Pull request by ShookLyngs**
### Description
Fixing issues #4 and #6, thanks to @jordanmack for pointing them out:
- [#4](https://github.com/godwokenrises/nft-bridge-ui/issues/4) - a state management problem caused by `useState` from react
- [#6](https://github.com/godwokenrises/nft-bridge-ui/issues/6) - the `early accessing` alert only appears in the transfer-ckb page

### Changes
- Refactor the style of alerts on the page
- Fix #4
- Fix #6

### Screenshots
image

### CODE REVIEW

**Review by Flouse — APPROVED** [review]

File: src/views/TransferNft/index.tsx [hunk 1]
```diff
@@ -21,21 +22,31 @@ export function TransferNftPage() {
...
+                  <li>Keep the TxHash after submission</li>
+                </ol>
+              </div>
+            </ToggleCollapse>
+            <ToggleCollapse title="Early Accessing">
+              <div className="text-slate-800">
+                The Godwoken NFT Bridge (beta) is still in early development, you may experience issues using the app.
+                If you find any issues, please <a className="text-emerald-600 underline" href="https://github.com/godwokenrises/nft-bridge-ui/issues" target="_blank">open an issue</a> to let us know.
+              </div>
+            </ToggleCollapse>
```
Comment (oriole-pub) [inline src/views/TransferNft/index.tsx:49]: If they appear on multiple pages, would it be more appropriate to encapsulate them again?

**Review by Dawn-githup — APPROVED** [review]

File: src/views/TransferNft/index.tsx (hunk 1 above)
Comment (oriole-pub) [reply src/views/TransferNft/index.tsx:49]: But for now, it doesn't seem to matter

**Review by oriole-pub — APPROVED** [review]

File: src/views/TransferNft/index.tsx (hunk 1 above)
Comment (ShookLyngs) [reply src/views/TransferNft/index.tsx:49]: This alert appears in multiple pages and it has two sets of styles, so I think we can leave it like this for now. 
But if we need to edit its content next time, we should create a component for it.
